remote: https://localhost:8080
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk1NDM1NDYsImlhdCI6MTY2OTU0MjY0NiwibG9naW4iOiJiaWxsIiwidXNlcl9pZCI6Ijc2ZjZjM2M1LThmYTctNDRkNy04YzBiLWI2ZTFhNjZjMjNjZCJ9.CgH4seVJ2g4fpHFLNvTNdjr42MKKXwKdBJoudyBNG-M
refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk1NDM1NDYsImlhdCI6MTY2OTU0MjY0NiwibG9naW4iOiJiaWxsIiwidXNlcl9pZCI6Ijc2ZjZjM2M1LThmYTctNDRkNy04YzBiLWI2ZTFhNjZjMjNjZCJ9.UViMQJFSdFymUFKXVjrlEEq-RWFnqRinnni8ZvsTT04
login: bill
